version: "3.8"

services:
  microservice-permissions-api:
    build: ./
    restart: always
    image: microservice-permissions-api
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: 7147
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/ms-permissions.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
    ports:
      - 7146:80
      - 7147:443
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https/
    depends_on:
      - rabbitmq
      - postgres
      - redis

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass password
    volumes:
      - redis:/var/lib/redis/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/data
      - ~/.docker-conf/rabbitmq/log/:/var/lib/rabbitmq/log

volumes:
  rabbitmq:
  postgres:
  pgadmin:
  redis:
