// <auto-generated />
using Microservice.Permissions.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Microservice.Permissions.Database.Migrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    [Migration("20220924211635_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microservice.Permissions.Kernel.Entities.AccessEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<int>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("area_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_accesses");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_accesses_application_id");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_accesses_area_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_accesses_role_id");

                    b.ToTable("accesses", (string)null);
                });

            modelBuilder.Entity("Microservice.Permissions.Kernel.Entities.ApplicationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("Microservice.Permissions.Kernel.Entities.AreaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_areas");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_areas_application_id");

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("Microservice.Permissions.Kernel.Entities.PermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessId")
                        .HasColumnType("integer")
                        .HasColumnName("access_id");

                    b.Property<bool>("HaveAccess")
                        .HasColumnType("boolean")
                        .HasColumnName("have_access");

                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("AccessId")
                        .HasDatabaseName("ix_permissions_access_id");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Microservice.Permissions.Kernel.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microservice.Permissions.Kernel.Entities.AccessEntity", b =>
                {
                    b.HasOne("Microservice.Permissions.Kernel.Entities.ApplicationEntity", "Application")
                        .WithMany("Accesses")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accesses_applications_application_id");

                    b.HasOne("Microservice.Permissions.Kernel.Entities.AreaEntity", "Area")
                        .WithMany("Accesses")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accesses_areas_area_id");

                    b.HasOne("Microservice.Permissions.Kernel.Entities.RoleEntity", "Role")
                        .WithMany("Accesses")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accesses_roles_role_id");

                    b.Navigation("Application");

                    b.Navigation("Area");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Microservice.Permissions.Kernel.Entities.AreaEntity", b =>
                {
                    b.HasOne("Microservice.Permissions.Kernel.Entities.ApplicationEntity", "Application")
                        .WithMany("Areas")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_areas_applications_application_id");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Microservice.Permissions.Kernel.Entities.PermissionEntity", b =>
                {
                    b.HasOne("Microservice.Permissions.Kernel.Entities.AccessEntity", "Access")
                        .WithMany("Permissions")
                        .HasForeignKey("AccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permissions_accesses_access_id");

                    b.Navigation("Access");
                });

            modelBuilder.Entity("Microservice.Permissions.Kernel.Entities.AccessEntity", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Microservice.Permissions.Kernel.Entities.ApplicationEntity", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("Areas");
                });

            modelBuilder.Entity("Microservice.Permissions.Kernel.Entities.AreaEntity", b =>
                {
                    b.Navigation("Accesses");
                });

            modelBuilder.Entity("Microservice.Permissions.Kernel.Entities.RoleEntity", b =>
                {
                    b.Navigation("Accesses");
                });
#pragma warning restore 612, 618
        }
    }
}
